import { useEffect, useState } from "react";
import {
  AlertCircle,
  Download,
  FileText,
  FileType,
  LoaderCircle,
  RefreshCw,
  Trash2,
} from "lucide-react";

import {
  deleteReport,
  downloadReport,
  listReports,
} from "../services/reportService.js";

function getErrorMessage(error, fallback) {
  const detail = error?.response?.data?.detail;
  return typeof detail === "string" ? detail : fallback;
}

function formatCreatedAt(value) {
  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(date);
}

function getFormatLabel(format) {
  return format?.toUpperCase() === "DOCX" ? "DOCX" : "PDF";
}

function ReportIcon({ format }) {
  const Icon =
    getFormatLabel(format) === "DOCX"
      ? FileType
      : FileText;

  return (
    <Icon
      size={21}
      strokeWidth={1.5}
    />
  );
}

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const [downloadingId, setDownloadingId] =
    useState(null);

  const [deletingId, setDeletingId] =
    useState(null);

  const [actionError, setActionError] =
    useState(null);

  async function fetchReports() {
    setLoading(true);
    setError(null);

    try {
      const response = await listReports();

      setReports(
        Array.isArray(response?.reports)
          ? response.reports
          : []
      );
    } catch (fetchError) {
      setError(
        getErrorMessage(
          fetchError,
          "Reports could not be loaded right now."
        )
      );
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    fetchReports();
  }, []);

  async function handleDownload(report) {
    if (downloadingId === report.report_id) {
      return;
    }

    setDownloadingId(report.report_id);
    setActionError(null);

    try {
      const blob = await downloadReport(
        report.report_id
      );

      const objectUrl =
        URL.createObjectURL(blob);

      const link =
        document.createElement("a");

      link.href = objectUrl;
      link.download = report.filename;

      document.body.appendChild(link);

      link.click();

      link.remove();

      URL.revokeObjectURL(objectUrl);
    } catch (downloadRequestError) {
      setActionError({
        reportId: report.report_id,
        message: getErrorMessage(
          downloadRequestError,
          "The report could not be downloaded."
        ),
      });
    } finally {
      setDownloadingId(null);
    }
  }

  async function handleDelete(report) {
    if (deletingId === report.report_id) {
      return;
    }

    const confirmed = window.confirm(
      `Delete "${report.filename}"? This will permanently remove the generated file.`
    );

    if (!confirmed) {
      return;
    }

    setDeletingId(report.report_id);
    setActionError(null);

    try {
      await deleteReport(
        report.report_id
      );

      setReports((currentReports) =>
        currentReports.filter(
          (item) =>
            item.report_id !==
            report.report_id
        )
      );
    } catch (deleteRequestError) {
      setActionError({
        reportId: report.report_id,
        message: getErrorMessage(
          deleteRequestError,
          "The report could not be deleted."
        ),
      });
    } finally {
      setDeletingId(null);
    }
  }

  return (
    <div className="mx-auto flex w-full max-w-6xl flex-col gap-6">
      <header className="border-b border-white/[0.08] pb-6">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center border border-cyan-200/15 bg-cyan-200/[0.06] text-cyan-100/80">
            <FileText
              size={19}
              strokeWidth={1.6}
            />
          </div>

          <div>
            <p className="text-[11px] uppercase tracking-[0.2em] text-cyan-200/55">
              AgentOS
            </p>

            <h1 className="mt-1 text-xl font-medium tracking-tight text-white/90">
              Reports
            </h1>
          </div>
        </div>

        <p className="mt-4 max-w-2xl text-sm leading-6 text-white/45">
          Download or manage reports generated by
          your AgentOS workflows.
        </p>
      </header>

      {actionError && (
        <div className="flex items-center gap-3 border border-red-300/15 bg-red-300/[0.05] px-4 py-3 text-sm leading-6 text-red-100/70">
          <AlertCircle
            size={16}
            className="shrink-0"
            strokeWidth={1.6}
          />

          <span>
            {actionError.message}
          </span>
        </div>
      )}

      <section className="border border-white/[0.08] bg-[#0b121d]/75 p-5 shadow-[0_20px_60px_rgba(0,0,0,0.14)] sm:p-7">
        <div className="mb-6 flex items-start justify-between gap-4">
          <div>
            <h2 className="text-sm font-medium tracking-wide text-white/90">
              Generated reports
            </h2>

            <p className="mt-2 text-xs leading-5 text-white/40">
              Your completed PDF and DOCX reports.
            </p>
          </div>

          {!loading &&
            !error &&
            reports.length > 0 && (
              <span className="shrink-0 text-[11px] uppercase tracking-[0.16em] text-teal-200/55">
                {reports.length}{" "}
                {reports.length === 1
                  ? "report"
                  : "reports"}
              </span>
            )}
        </div>

        {loading ? (
          <div className="flex min-h-56 items-center justify-center gap-3 text-sm text-cyan-100/55">
            <LoaderCircle
              size={17}
              className="animate-spin"
              strokeWidth={1.6}
            />

            Loading reports...
          </div>
        ) : error ? (
          <div className="flex min-h-56 flex-col items-center justify-center border border-red-300/15 bg-red-300/[0.04] px-6 text-center">
            <AlertCircle
              size={22}
              className="text-red-100/65"
              strokeWidth={1.5}
            />

            <p className="mt-4 text-sm text-red-100/75">
              {error}
            </p>

            <button
              type="button"
              onClick={fetchReports}
              className="mt-5 flex h-10 items-center gap-2 border border-white/[0.12] px-4 text-xs text-white/65 transition-colors hover:border-cyan-200/30 hover:text-cyan-100/85"
            >
              <RefreshCw
                size={14}
                strokeWidth={1.6}
              />

              Try again
            </button>
          </div>
        ) : reports.length === 0 ? (
          <div className="flex min-h-56 flex-col items-center justify-center border border-dashed border-white/[0.1] px-6 text-center">
            <FileText
              size={24}
              className="text-cyan-100/45"
              strokeWidth={1.4}
            />

            <h3 className="mt-4 text-sm font-medium text-white/75">
              No reports yet
            </h3>

            <p className="mt-2 max-w-sm text-xs leading-5 text-white/35">
              Generated reports will appear here
              when your workflows are complete.
            </p>
          </div>
        ) : (
          <div className="divide-y divide-white/[0.07] border border-white/[0.08] bg-[#080e17]/65">
            {reports.map((report) => {
              const isDownloading =
                downloadingId ===
                report.report_id;

              const isDeleting =
                deletingId ===
                report.report_id;

              return (
                <div
                  key={report.report_id}
                  className="flex items-center gap-4 px-4 py-4 sm:px-5"
                >
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center border border-cyan-200/15 bg-cyan-200/[0.05] text-cyan-100/70">
                    <ReportIcon
                      format={report.format}
                    />
                  </div>

                  <div className="min-w-0 flex-1">
                    <p
                      className="truncate text-sm text-white/80"
                      title={report.filename}
                    >
                      {report.filename}
                    </p>

                    <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-white/35">
                      <span>
                        {getFormatLabel(
                          report.format
                        )}
                      </span>

                      <span className="hidden h-1 w-1 rounded-full bg-white/25 sm:block" />

                      <span>
                        {formatCreatedAt(
                          report.created_at
                        )}
                      </span>
                    </div>
                  </div>

                  <button
                    type="button"
                    onClick={() =>
                      handleDownload(report)
                    }
                    disabled={
                      isDownloading ||
                      isDeleting
                    }
                    aria-label={`Download ${report.filename}`}
                    title="Download report"
                    className="flex h-9 w-9 shrink-0 items-center justify-center border border-cyan-200/15 text-cyan-100/70 transition-colors hover:border-cyan-200/35 hover:bg-cyan-200/[0.07] hover:text-cyan-50 disabled:cursor-wait disabled:opacity-50"
                  >
                    {isDownloading ? (
                      <LoaderCircle
                        size={14}
                        className="animate-spin"
                        strokeWidth={1.6}
                      />
                    ) : (
                      <Download
                        size={14}
                        strokeWidth={1.6}
                      />
                    )}
                  </button>

                  <button
                    type="button"
                    onClick={() =>
                      handleDelete(report)
                    }
                    disabled={
                      isDownloading ||
                      isDeleting
                    }
                    aria-label={`Delete ${report.filename}`}
                    title="Delete report"
                    className="flex h-9 w-9 shrink-0 items-center justify-center border border-red-200/10 text-red-100/55 transition-colors hover:border-red-200/25 hover:bg-red-200/[0.06] hover:text-red-100/80 disabled:cursor-wait disabled:opacity-50"
                  >
                    {isDeleting ? (
                      <LoaderCircle
                        size={14}
                        className="animate-spin"
                        strokeWidth={1.6}
                      />
                    ) : (
                      <Trash2
                        size={14}
                        strokeWidth={1.6}
                      />
                    )}
                  </button>
                </div>
              );
            })}
          </div>
        )}
      </section>
    </div>
  );
}